AssignmentEcommerce_CustomerSite/Controllers/CartsController.cs
using AssignmentEcommerce_CustomerSite.Services;
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartApiClient _cartApiClient;

        public CartsController(ICartApiClient cartApiClient)
        {
            _cartApiClient = cartApiClient;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var carts = await _cartApiClient.GetCart();
            ViewBag.Carts = carts;
            ViewBag.Total = carts.Sum(x => x.Price * x.Quantity);
            ViewBag.TotalItem = carts.Count();

            if(carts.Count() < 1)
            {
                ViewBag.CartNull = "Your cart is empty !";
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddToCart(string productId, int quantity)
        {
            var cartItem = new CartCreateRequest
            {
                ProductId = productId,
                Quantity = quantity
            };

            await _cartApiClient.PostCart(cartItem);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> RemoveCart(string id)
        {
            await _cartApiClient.RemoveCart(id);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdateCart(string cartDetailId, int quantity)
        {
            var cartItem = new CartUpdateRequest
            {
                CartDetailId = cartDetailId,
                Quantity = quantity
            };

            await _cartApiClient.UpdateCart(cartItem);

            return RedirectToAction("Index");
        }
    }
}

AssignmentEcommerce_CustomerSite/Controllers/ProductController.cs
using AssignmentEcommerce_CustomerSite.Services;
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productClient;
        private readonly ICategoryApiClient _categoryClient;

        public ProductController(IProductApiClient productClient, ICategoryApiClient categoryClient)
        {
            _productClient = productClient;
            _categoryClient = categoryClient;
        }

        public async Task<IActionResult> Index(string id)
        {
            if (id != null)
            {
                var productByCate = await _productClient.GetProductByCategory(id);
                ViewBag.Products = productByCate;
                ViewBag.SearchBy = productByCate[0].NameCategory;
            }
            else
            {
                var products = await _productClient.GetProduct();
                ViewBag.Products = products;
                ViewBag.SearchBy = "All products";
            }

            return View();
        }

        public async Task<IActionResult> Detail(string id)
        {
            var product = await _productClient.GetProductById(id);

            var reviews = await _productClient.GetReviews(id);
            ViewBag.ReviewsCount = reviews.Count();
            ViewBag.Reviews = reviews;

            var productsSameCate = await _productClient.GetProductSameCategory(id);
            ViewBag.ProductsSameCate = productsSameCate;

            return View(product);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostReview(string userName, int rating, string content, string productId)
        {
            var review = new ReviewFormRequest
            {
                UserName = userName,
                Content = content,
                Rating = rating,
                ProductId = productId,
            };

            await _productClient.PostReview(review);

            return RedirectToAction("Detail", new { id = productId });
        }
    }
}

AssignmentEcommerce_CustomerSite/ViewComponents/CategoryMenuViewComponent.cs
using AssignmentEcommerce_CustomerSite.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoryMenuViewComponent(ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categorys = await _categoryApiClient.GetCategory();

            return View("Default", categorys);
        }
    }
}

AssignmentEcommerce_CustomerSite/Views/Shared/_Footer.cshtml
<footer>
    <div class="about">
        <div class="container">
            <div class="row">
                <hr class="offset-md">

                <div class="col-xs-6 col-sm-3">
                    <div class="item">
                        <i class="ion-ios-telephone-outline"></i>
                        <h1>24/7 free <br> <span>support</span></h1>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3">
                    <div class="item">
                        <i class="ion-ios-star-outline"></i>
                        <h1>Low price <br> <span>guarantee</span></h1>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3">
                    <div class="item">
                        <i class="ion-ios-gear-outline"></i>
                        <h1> Manufacturer’s <br> <span>warranty</span></h1>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3">
                    <div class="item">
                        <i class="ion-ios-loop"></i>
                        <h1> Full refund <br> <span>guarantee</span> </h1>
                    </div>
                </div>

                <hr class="offset-md">
            </div>
        </div>
    </div>

    <div class="container">
        <hr class="offset-md">

        <div class="row menu">
            <div class="col-sm-3 col-md-2">
                <h1 class="h4">Information <i class="ion-plus-round hidden-sm hidden-md hidden-lg"></i> </h1>

                <div class="list-group">
                    <a href="#" class="list-group-item">About</a>
                    <a href="#" class="list-group-item">Terms</a>
                    <a href="#" class="list-group-item">How to order</a>
                    <a href="#" class="list-group-item">Delivery</a>
                </div>
            </div>
            <div class="col-sm-3 col-md-2">
                <h1 class="h4">Products <i class="ion-plus-round hidden-sm hidden-md hidden-lg"></i> </h1>

                <div class="list-group">
                    <a href="#" class="list-group-item">Laptops</a>
                    <a href="#" class="list-group-item">Tablets</a>
                    <a href="#" class="list-group-item">Servers</a>
                </div>
            </div>
            <div class="col-sm-3 col-md-2">
                <h1 class="h4">Support <i class="ion-plus-round hidden-sm hidden-md hidden-lg"></i> </h1>

                <div class="list-group">
                    <a href="#" class="list-group-item">Returns</a>
                    <a href="#" class="list-group-item">FAQ</a>
                    <a href="#" class="list-group-item">Contacts</a>
                </div>
            </div>
            <div class="col-sm-3 col-md-2">
                <h1 class="h4">Location</h1>

                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Language
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#English"> <img src="~/Template/assets/img/flags/gb.png" alt="Eng" /> English</a></li>
                        <li><a href="#Spanish"> <img src="~/Template/assets/img/flags/es.png" alt="Spa" /> Spanish</a></li>
                        <li><a href="#Deutch"> <img src="~/Template/assets/img/flags/de.png" alt="De" /> Deutch</a></li>
                        <li><a href="#French"> <img src="~/Template/assets/img/flags/fr.png" alt="Fr" /> French</a></li>
                    </ul>
                </div>
                <hr class="offset-xs">

                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Currency
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <li><a href="#Euro"><i class="ion-social-euro"></i> Euro</a></li>
                        <li><a href="#Dollar"><i class="ion-social-usd"></i> Dollar</a></li>
                        <li><a href="#Yen"><i class="ion-social-yen"></i> Yen</a></li>
                        <li><a href="#Bitcoin"><i class="ion-social-bitcoin"></i> Bitcoin</a></li>
                    </ul>
                </div>

            </div>
            <div class="col-sm-3 col-md-3 col-md-offset-1 align-right hidden-sm hidden-xs">
                <h1 class="h4">Unistore, Inc.</h1>

                <address>
                    364 Cong Hoa Street, Tan Binh District<br>
                    Ho Chi Minh City<br>
                    (123) 456-7890
                </address>

                <address>
                    <strong>Support</strong><br>
                    <a href="#">support@gmail.com</a>
                </address>

            </div>
        </div>
    </div>

    <hr>

    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9 payments">
                <p>Pay your order in the most convenient way</p>

                <div class="payment-icons">
                    <img src="~/Template/assets/img/payments/paypal.svg" alt="paypal">
                    <img src="~/Template/assets/img/payments/visa.svg" alt="visa">
                    <img src="~/Template/assets/img/payments/master-card.svg" alt="mc">
                    <img src="~/Template/assets/img/payments/discover.svg" alt="discover">
                    <img src="~/Template/assets/img/payments/american-express.svg" alt="ae">
                </div>
                <br>

            </div>
        </div>
    </div>
</footer>

AssignmentEcommerce_CustomerSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Unistore</title>

    <meta name="description" content="Bootstrap template for you store - E-Commerce Bootstrap Template">
    <meta name="keywords" content="unistore, e-commerce bootstrap template, premium e-commerce bootstrap template, premium bootstrap template, bootstrap template, e-commerce, bootstrap template, sunrise digital">
    <meta name="author" content="Sunrise Digital">

    <!-- Bootstrap -->
    <link href="~/Template/assets/css/bootstrap.css" rel="stylesheet">
    <link href="~/Template/assets/css/custom.css" rel="stylesheet">
    <link href="~/Template/assets/css/carousel.css" rel="stylesheet">
    <link href="~/Template/assets/css/carousel-recommendation.css" rel="stylesheet">
    <link href="~/Template/assets/ionicons-2.0.1/css/ionicons.css" rel="stylesheet">
    <link href="~/css/Rating.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Catamaran:400,100,300' rel='stylesheet' type='text/css'>
</head>
<body>
    <!-- Navbar -->
    <partial name="_Navbar" />

    <div>
        @RenderBody()
    </div>

    <!-- Footer -->
    <partial name="_Footer" />

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Template/assets/js/jquery-latest.min.js"></script>

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Template/assets/js/bootstrap.min.js"></script>
    <script src="~/Template/assets/js/core.js"></script>
    <script src="~/Template/assets/js/carousel.js"></script>
    <script src="~/Template/assets/js/carousel-recommendation.js"></script>
    <script src="~/Template/assets/js/catalog.js"></script>
    <script type="text/javascript" src="~/Template/assets/js/jquery-ui-1.11.4.js"></script>
    <script type="text/javascript" src="~/Template/assets/js/jquery.ui.touch-punch.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AssignmentEcommerce_CustomerSite/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"> <i class="ion-cube"></i> Unistore</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Product" asp-action="Index" asp-route-id="">Product</a></li>
                <li class="dropdown">
                    @await Component.InvokeAsync("CategoryMenu")
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a><span><i class="ion-ios-contact"></i> @User.Identity.Name</span></a></li>
                    <li><a asp-controller="Carts" asp-action="Index"><i class="ion-android-cart"></i> Cart </a></li>
                    <li><a asp-controller="Account" asp-action="SignOut"> <i class="ion-android-exit"></i> Logout </a></li>
                }
                else
                {   
                    <li><a asp-controller="Account" asp-action="SignIn"> <i class="ion-android-person"></i> Login </a></li>
                }
            </ul>
        </div>
    </div>
</nav>