AssignmentEcommerce_CustomerSite/Controllers/CartsController.cs
using AssignmentEcommerce_CustomerSite.Services;
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartApiClient _cartApiClient;

        public CartsController(ICartApiClient cartApiClient)
        {
            _cartApiClient = cartApiClient;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var carts = await _cartApiClient.GetCart();
            ViewBag.Carts = carts;
            ViewBag.Total = carts.Sum(x => x.Price * x.Quantity);
            ViewBag.TotalItem = carts.Count();

            if(carts.Count() < 1)
            {
                ViewBag.CartNull = "Your cart is empty !";
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddToCart(string productId, int quantity)
        {
            var cartItem = new CartCreateRequest
            {
                ProductId = productId,
                Quantity = quantity
            };

            await _cartApiClient.PostCart(cartItem);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> RemoveCart(string id)
        {
            await _cartApiClient.RemoveCart(id);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdateCart(string cartDetailId, int quantity)
        {
            var cartItem = new CartUpdateRequest
            {
                CartDetailId = cartDetailId,
                Quantity = quantity
            };

            await _cartApiClient.UpdateCart(cartItem);

            return RedirectToAction("Index");
        }
    }
}

AssignmentEcommerce_CustomerSite/ViewComponents/CartItemViewComponent.cs
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.ViewComponents
{
    public class CartItemViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(CartRespond cartRespond)
        {
            return await Task.FromResult(View("Default", cartRespond));
        }
    }
}

AssignmentEcommerce_CustomerSite/Views/Carts/Index.cshtml
<hr class="offset-md">

<div class="box">
    <div class="container">
        <h1>Shopping Cart</h1>
        <hr class="offset-sm">
    </div>
</div>
<hr class="offset-md">

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="checkout-cart">
                        <div class="content">
                            @if (ViewBag.TotalItem < 1)
                            {
                                <h2>@ViewBag.CartNull</h2>
                            }
                            else
                            {
                                @foreach (var cartItem in ViewBag.Carts)
                                {
                                    @await Component.InvokeAsync("CartItem", cartItem);
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 col-md-4">
            <hr class="offset-md visible-sm">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="no-margin">Summary</h2>
                    <hr class="offset-md">

                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-6">
                                <p>Subtotal (@ViewBag.TotalItem items)</p>
                            </div>
                            <div class="col-xs-6">
                                <p><b>@Convert.ToDecimal(ViewBag.Total).ToString("#,##") VND</b></p>
                            </div>

                            <div class="col-xs-6">
                                <p>Discount</p>
                            </div>
                            <div class="col-xs-6">
                                <p><b>0 VND</b></p>
                            </div>

                            <div class="col-xs-6">
                                <p>Tax</p>
                            </div>
                            <div class="col-xs-6">
                                <p><b>0 VND</b></p>
                            </div>
                        </div>
                    </div>
                    <hr>

                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-6">
                                <h5 class="no-margin">Total sum</h5>
                            </div>
                            <div class="col-xs-6">
                                <h4 class="no-margin">@Convert.ToDecimal(ViewBag.Total).ToString("#,##") VND</h4>
                            </div>
                        </div>
                    </div>
                    <hr class="offset-md">

                    <a href="../checkout/" class="btn btn-primary btn-lg justify"><i class="ion-android-checkbox-outline"></i>&nbsp;&nbsp; Checkout order</a>
                    <hr class="offset-md">
                </div>
            </div>
        </div>
    </div>
</div>