AssignmentEcommerce_CustomerSite/Controllers/CartsController.cs
using AssignmentEcommerce_CustomerSite.Services;
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartApiClient _cartApiClient;

        public CartsController(ICartApiClient cartApiClient)
        {
            _cartApiClient = cartApiClient;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var carts = await _cartApiClient.GetCart();
            ViewBag.Carts = carts;
            ViewBag.Total = carts.Sum(x => x.Price * x.Quantity);
            ViewBag.TotalItem = carts.Count();

            if(carts.Count() < 1)
            {
                ViewBag.CartNull = "Your cart is empty !";
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddToCart(string productId, int quantity)
        {
            var cartItem = new CartCreateRequest
            {
                ProductId = productId,
                Quantity = quantity
            };

            await _cartApiClient.PostCart(cartItem);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> RemoveCart(string id)
        {
            await _cartApiClient.RemoveCart(id);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdateCart(string cartDetailId, int quantity)
        {
            var cartItem = new CartUpdateRequest
            {
                CartDetailId = cartDetailId,
                Quantity = quantity
            };

            await _cartApiClient.UpdateCart(cartItem);

            return RedirectToAction("Index");
        }
    }
}

AssignmentEcommerce_CustomerSite/Controllers/ProductController.cs
using AssignmentEcommerce_CustomerSite.Services;
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productClient;
        private readonly ICategoryApiClient _categoryClient;

        public ProductController(IProductApiClient productClient, ICategoryApiClient categoryClient)
        {
            _productClient = productClient;
            _categoryClient = categoryClient;
        }

        public async Task<IActionResult> Index(string id)
        {
            if (id != null)
            {
                var productByCate = await _productClient.GetProductByCategory(id);
                ViewBag.Products = productByCate;
                ViewBag.SearchBy = productByCate[0].NameCategory;
            }
            else
            {
                var products = await _productClient.GetProduct();
                ViewBag.Products = products;
                ViewBag.SearchBy = "All products";
            }

            return View();
        }

        public async Task<IActionResult> Detail(string id)
        {
            var product = await _productClient.GetProductById(id);

            var reviews = await _productClient.GetReviews(id);
            ViewBag.ReviewsCount = reviews.Count();
            ViewBag.Reviews = reviews;

            var productsSameCate = await _productClient.GetProductSameCategory(id);
            ViewBag.ProductsSameCate = productsSameCate;

            return View(product);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostReview(string userName, int rating, string content, string productId)
        {
            var review = new ReviewFormRequest
            {
                UserName = userName,
                Content = content,
                Rating = rating,
                ProductId = productId,
            };

            await _productClient.PostReview(review);

            return RedirectToAction("Detail", new { id = productId });
        }
    }
}

AssignmentEcommerce_CustomerSite/ViewComponents/ProductCardViewComponent.cs
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.ViewComponents
{
    public class ProductCardViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(ProductVm product)
        {         
            return await Task.FromResult(View("Default", product));
        }
    }
}

AssignmentEcommerce_CustomerSite/ViewComponents/ReviewContentViewComponent.cs
using AssignmentEcommerce_Shared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssignmentEcommerce_CustomerSite.ViewComponents
{
    public class ReviewContentViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(ReviewVm review)
        {
            return await Task.FromResult(View("Default", review));
        }
    }
}

AssignmentEcommerce_CustomerSite/Views/Product/Detail.cshtml
@model AssignmentEcommerce_Shared.ProductVm

<hr class="offset-lg">
<div class="product">
    <div class="container">
        <div class="row">
            <div class="col-sm-7 col-md-7">
                <div class="carousel product" data-count="5" data-current="1">
                    <div class="items">
                        <div class="item active" data-marker="1">
                            <img src="@Model.Images" alt="@Model.Name" />
                        </div>
                    </div>

                    <ul class="markers">
                        <li data-marker="1" class="active"><img src="@Model.Images" alt="@Model.Name" /></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-5 col-md-5">
                <h2>@Model.NameCategory</h2>
                <h1>@Model.Name</h1>
                <h3>
                    @for (int i = 0; i < Model.Rating; i++)
                    {
                        <i class="ion-android-star" style="color: #ffdd59"></i>
                    }
                </h3>

                <p class="price">@Convert.ToDecimal(Model.Price).ToString("#,##") VND</p>
                <br><br>

                @if (User.Identity.IsAuthenticated)
                {
                    <form asp-action="AddToCart" asp-controller="Carts" method="post">
                        <input name="productId" type="hidden" value="@Model.ProductId" />
                        <input name="quantity" type="hidden" value="1" />
                        <button type="submit" class="btn btn-primary btn-rounded btn-sm"> <i class="ion-bag"></i> Add to cart</button>
                    </form>
                }
                else
                {
                    <button data-toggle="modal" data-target="#myModal" class="btn btn-primary btn-rounded btn-sm"> <i class="ion-bag"></i> Add to cart</button>
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <div class="text-center">
                                        <h3>Please login before add to cart !</h3>
                                        <a asp-controller="Account" asp-action="SignIn"> Login </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <br><br><br>


        <div class="row">
            <div class="col-sm-7">
                <h1>@Model.Name</h1>
                <br>
                <p>@Model.Description</p>
                <br>

                <h2>Product specifications</h2>
                <br>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Operating system</label> </div>
                    <div class="col-sm-6"> <p>Chrome OS™</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Processor</label> </div>
                    <div class="col-sm-6"> <p>Intel® Celeron® N2840 with Intel® HD Graphics (2.16 GHz, up to 2.58 GHz, 1 MB cache, 2 cores)</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Processor technology</label> </div>
                    <div class="col-sm-6"> <p>Intel Turbo Boost Technology</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Graphics</label> </div>
                    <div class="col-sm-6"> <p>Intel HD Graphics</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Memory</label> </div>
                    <div class="col-sm-6"> <p>2 GB DDR3L SDRAM (onboard)</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Hard drive</label> </div>
                    <div class="col-sm-6"> <p>16 GB eMMC</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Wireless</label> </div>
                    <div class="col-sm-6"> <p>802.11ac (2x2) and Bluetooth® 4.0 combo</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Power supply</label> </div>
                    <div class="col-sm-6"> <p>45 W AC power adapter</p> </div>
                </div>

                <div class="row specification">
                    <div class="col-sm-6"> <label>Battery</label> </div>
                    <div class="col-sm-6"> <p>3-cell, 36 Wh Li-ion</p> </div>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="comments">
                    <h2 class="h3">What do you think? (#@ViewBag.ReviewsCount)</h2>
                    <div class="wrapper">
                        <div class="content">
                            @foreach (var review in ViewBag.Reviews)
                            {
                                @await Component.InvokeAsync("ReviewContent", review);
                            }
                        </div>
                    </div>
                    <br>
                    <button class="btn btn-default btn-sm" data-toggle="modal" data-target="#Modal-Comment"> <i class="ion-chatbox-working"></i> Add comment </button>
                </div>
                <br><br>

                <div class="talk">
                    <h2 class="h3">Do you have any questions?</h2>
                    <p>Online chat with our manager</p>

                    <button class="btn btn-default btn-sm" data-toggle="modal" data-target="#Modal-Talk"> <i class="ion-android-contact"></i> Lat's talk </button>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>

<section class="products">
    <div class="container">
        <h1 class="h3">Recommendation for you</h1>

        <div class="row">
            @foreach (var product in ViewBag.ProductsSameCate)
            {
                @await Component.InvokeAsync("ProductCard", product);
            }
        </div>
    </div>
</section>
<br>
<br>

<div class="modal fade" id="Modal-Comment" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header align-center">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="ion-android-close"></i></span></button>
                <h1 class="h4 modal-title">Add your comment</h1>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form class="join" asp-action="PostReview" asp-controller="Product" method="post">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="rate">
                                        <input type="radio" id="star5" name="rating" value="5" />
                                        <label for="star5" title="text">5 stars</label>
                                        <input type="radio" id="star4" name="rating" value="4" />
                                        <label for="star4" title="text">4 stars</label>
                                        <input type="radio" id="star3" name="rating" value="3" />
                                        <label for="star3" title="text">3 stars</label>
                                        <input type="radio" id="star2" name="rating" value="2" />
                                        <label for="star2" title="text">2 stars</label>
                                        <input type="radio" id="star1" name="rating" value="1" />
                                        <label for="star1" title="text">1 star</label>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <input type="text" name="userName" value="" placeholder="Name" required class="form-control" />
                                    <input type="hidden" name="productId" value="@Model.ProductId" />
                                    <br>
                                </div>
                                <div class="col-sm-12">
                                    <textarea name="content" placeholder="Type here" required class="form-control" rows="5"></textarea>
                                    <br>
                                </div>
                                <div class="col-sm-12">
                                    <div class="align-center">
                                        <br>
                                        <button type="submit" class="btn btn-primary btn-sm"> <i class="ion-android-send"></i> Send</button>
                                        <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal"> <i class="ion-android-share"></i> No, thanks </button>
                                        <br><br>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                    else
                    {
                        <div class="text-center">
                            <h3 class="text-center">Please login before comment the product !</h3>
                            <a asp-controller="Account" asp-action="SignIn"> Login </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Modal-Talk" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header align-center">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="ion-android-close"></i></span></button>
                <h1 class="h4 modal-title">Talk</h1>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="text-center">
                        <h3 class="text-center">We don't talk anymore - Charlie Puth !</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AssignmentEcommerce_CustomerSite/Views/Product/Index.cshtml
<hr class="offset-lg">
<div class="container tags">

    @*<div class="btn-group pull-right">
        <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ion-arrow-down-b"></i> Sorting by name
        </button>
        <ul class="dropdown-menu">
            <li class="active"><a href="#"> <i class="ion-arrow-down-c"></i> Name [A-Z]</a></li>
            <li><a href="#"> <i class="ion-arrow-up-c"></i> Name [Z-A]</a></li>
            <li><a href="#"> <i class="ion-arrow-down-c"></i> Price [Low-High]</a></li>
            <li><a href="#"> <i class="ion-arrow-up-c"></i> Price [High-Low]</a></li>
        </ul>
    </div>*@

    <p>Search by tags</p>
    <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-default btn-xs active">
            <input type="radio" name="options" id="option1" checked> @ViewBag.SearchBy
        </label>
    </div>
</div>

<div class="container">
    <div class="row">
        <!-- Products -->
        <div class="col-sm-12 products">
            <div class="row">
                @foreach (var product in ViewBag.Products)
                {
                    @await Component.InvokeAsync("ProductCard", product);
                }
            </div>

            <nav>
                <ul class="pagination">
                    <li>
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true"><i class="ion-ios-arrow-left"></i></span>
                        </a>
                    </li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li class="disabled"><a href="#">..</a></li>
                    <li><a href="#">10</a></li>
                    <li>
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true"><i class="ion-ios-arrow-right"></i></span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>